sudo: false
language: node_js
node_js: 
- 11
- 12
- 13
- stable
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - libjpeg-dev
      - librsvg2-dev
      - calibre
      - g++
